apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-intake-api.fullname" . }}
  labels: {{- include "telemetry-intake-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "telemetry-intake-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
