{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "telemetry-intake-api.serviceAccountName" . }}
  labels: {{- include "telemetry-intake-api.labels" . | nindent 4 }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}